#服务端口
server:
  port: 8200
spring:
  application:
    #服务名称
    name: sys-service-impl
  #eureka 权限配置
  security:
    basic:
      enabled: true
    user:
      name: jinfeng
      password: jinfeng
  #数据源配置
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://13.13.13.58:3306/cmcc_db_test?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
    ###################以下为druid增加的配置###########################
    #下面为连接池的补充设置,应用到上面所有数据源中
    #初始化大小，最小,最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    #配置获取连接等待超时的时间
    maxWait: 60000
    #配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间,单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache,并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #配置监控统计拦截的filters,去掉后监控界面sql无法统计,'wall'用于防火墙,此处是filter修改的地方
    filters:
      commons-log.connection-logger-name: stat,wall,log4j
    #通过connectProperties属性来打开mergeSql功能;慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  #aop配置
  aop:
    auto: true
  mvc:
    view:
      prefix: /
      suffix: .jsp
  thymeleaf:
    encoding: utf-8
    cache: false
    mode: html5
#mybatis映射文件配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
##服务注册到eureka地址
#eureka连接信息
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8100/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8101/eureka/
#swagger配置
swagger:
  base-package: com.yinda
  title:
  description:
  version: v1.0
  terms-of-service-url: 127.0.0.1:8101/swagger-ui.html
  contact:
    url:
    name: zengling
    email: 17363645521@163.com
#日志配置
logging:
  level:
    root: info
    com.yinda: debug
    org.springframework.security: warn
    # 默认日志文件名
    file: log
    # 默认日志路径
    path: ./log
  config: "classpath:log4j.xml"

