spring:
  application:
    name: basic-eureka-server
  #eureka 权限配置
  security:
    basic:
      enabled: true
    user:
      name: jinfeng
      password: jinfeng
#服务端口号
server:
  port: 8100
#eureka基本信息配置
eureka:
  instance:
    #注册到eureka ip地址
    hostname: 127.0.0.1
  client:
    #因为自己是为注册中心,不需要自己注册自己(集群为true单机false)
    register-with-eureka: true
    #因为自己是为注册中心,不需要检索服务(集群为true单机false)
    fetch-registry: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8101/eureka/
      #defaultZone: http://jinfeng:jinfeng@127.0.0.1:8101/eureka/
      #剔除失效服务间隔
      eviction-interval-timer-in-ms: 2000
    server:
      #是否开启安全保护,默认是开启的,如果默认开启,注册中心的服务列表就算有些服务断开了,也会继续保存
      enable-self-preservation: false
